### ISSUE TITLE
confuse about pin mux

### ISSUE THREAD

**Issue by standback** [simplefoc/Arduino-SimpleFOCShield#7]
hi guys.
i have question about  "Customizing pinout",
In the docs. 
![image](https://user-images.githubusercontent.com/920696/146706678-cbbaa704-9087-4282-8170-c4781e6019ed.png)
pwmA mapping to pin 9/10
pwmB mapping to pin 3/5

But , according the  note below
`
Now, there is a lot of possible pin configurations and not all of them are possible depending on the microcontroller and sensor you are using. For example, Arduino UNO only has 2 external interrupt pins, and they are pin 2 and 3. Therefore when using the board with Arduino UNO and Encoder we will try to use pin 3 for encoder channel A and not for pwm A.`
it seems mean that  PwmA should  mapping to pin3  instand 9/10.
version2.03 board ,also design that pinA mapping to pin 3/5.
![image](https://user-images.githubusercontent.com/920696/146706911-bc21bc22-e6a8-4ae1-ad87-acd78e3950b2.png)

is that means  this pinmux(in docs) is  out of date?

I am confused. 
![image](https://user-images.githubusercontent.com/920696/146707094-2db179e2-a7d6-441e-96fe-5128adeec832.png)
,
![image](https://user-images.githubusercontent.com/920696/146707110-64bb1275-527e-4630-a5cb-27df1f06cc68.png)
which one is right?

**Comment by askuric** [comment]
Yeah, it's the docs. It was an example pin out for the earlier version of the board.
Whatever is indicated on the board itself is the right configuration.

We try to keep the docs as up-to-date as possible, but these kinds of stuff are sometimes difficult to detect :)

We'll update it as soon as possible.

**Comment by standback** [comment]
Got it,  thanks for your reply.
